name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - cartopy
    - cdsapi
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - cdo
    - cartopy
    - metpy
    - netCDF4
